name: Deploy Schema for Production Database

on:
  push:
    paths:
      - ../../packages/prisma/src/migrations/**
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install pNPM
        usues: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install Dependencies
        uses: pnpm install
      - name: Apply All Pending Migrations to The Database
        run: pnpm dlx prisma migrate dev
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
